-- Junction table to link campaigns to items
-- This allows items to be associated with specific campaigns (e.g., seasonal menus)
create table public.campaign_items (
  id                bigint generated by default as identity primary key,
  campaign_id       bigint not null references public.campaigns(id) on delete cascade,
  item_id           bigint not null references public.items(id) on delete cascade,
  created_at        timestamptz not null default now(),
  unique (campaign_id, item_id)
);

create index campaign_items_campaign_id_idx on public.campaign_items (campaign_id);
create index campaign_items_item_id_idx on public.campaign_items (item_id);

-- Enable RLS on campaign_items
alter table public.campaign_items enable row level security;

-- RLS policies for campaign_items (same pattern as other tables)
create policy "Allow authenticated users to read campaign_items"
  on public.campaign_items for select
  to authenticated
  using (true);

create policy "Allow authenticated users to insert campaign_items"
  on public.campaign_items for insert
  to authenticated
  with check (true);

create policy "Allow authenticated users to update campaign_items"
  on public.campaign_items for update
  to authenticated
  using (true)
  with check (true);

create policy "Allow authenticated users to delete campaign_items"
  on public.campaign_items for delete
  to authenticated
  using (true);

-- Enable realtime for campaign_items
alter publication supabase_realtime add table public.campaign_items;
