-- 1. Campaigns: each event/session (e.g. “Sunday Pop-up 2025-11-28”)
create table public.campaigns (
  id                bigint generated by default as identity primary key,
  name              text not null,
  starts_at         timestamptz,
  ends_at           timestamptz,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now()
);

-- 2. Categories: maps to kitchen “queues” (Bagels, Lattes, etc.)
create table public.categories (
  id                bigint generated by default as identity primary key,
  name              text not null unique,       -- e.g. 'Bagels', 'Drinks'
  slug              text not null unique,       -- e.g. 'bagels', 'drinks'
  display_order     integer not null default 0, -- for UI sorting
  created_at        timestamptz not null default now()
);

-- 3. Items: menu items (bagel, latte, etc.), each belongs to a category
create table public.items (
  id                bigint generated by default as identity primary key,
  category_id       bigint not null references public.categories(id) on delete restrict,
  name              text not null,              -- 'Plain Bagel', 'Latte'
  description       text,
  image_url         text,
  base_price        numeric(10,2) not null default 0.00,
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index items_category_id_idx on public.items (category_id);
create index items_is_active_idx on public.items (is_active);

-- 4. Modifiers: catalog of modifiers.
-- You can create new ones on the fly at the terminal by inserting here.
create table public.modifiers (
  id                bigint generated by default as identity primary key,
  name              text not null,              -- 'Extra Shot', 'No Cheese', 'Iced'
  description       text,
  price_delta       numeric(10,2) not null default 0.00, -- +/- from base_price
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index modifiers_is_active_idx on public.modifiers (is_active);

-- 5. Item_Modifiers: which modifiers are allowed for which items (optional).
-- This powers the terminal UI (only show relevant modifiers for an item).
create table public.item_modifiers (
  id                bigint generated by default as identity primary key,
  item_id           bigint not null references public.items(id) on delete cascade,
  modifier_id       bigint not null references public.modifiers(id) on delete restrict,
  created_at        timestamptz not null default now(),
  unique (item_id, modifier_id)
);

create index item_modifiers_item_id_idx on public.item_modifiers (item_id);
create index item_modifiers_modifier_id_idx on public.item_modifiers (modifier_id);

-- 6. Orders: top-level order record.
create table public.orders (
  id                bigint generated by default as identity primary key,
  campaign_id       bigint references public.campaigns(id) on delete set null,
  customer_name     text not null,              -- 'Alice', 'Bob', etc.
  status            text not null default 'new',-- 'new','in_progress','ready','picked_up','cancelled',...
  subtotal          numeric(10,2) not null default 0.00,
  notes             text,                       -- optional (e.g., general order notes)
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Optional: status guard without enums
alter table public.orders add constraint orders_status_check
  check (status in ('new', 'in_progress', 'ready', 'picked_up', 'cancelled'));

create index orders_campaign_id_idx on public.orders (campaign_id);
create index orders_status_idx on public.orders (status);
create index orders_created_at_idx on public.orders (created_at);

-- 7. Order_Items: line items in an order.
create table public.order_items (
  id                bigint generated by default as identity primary key,
  order_id          bigint not null references public.orders(id) on delete cascade,
  item_id           bigint not null references public.items(id) on delete restrict,
  quantity          integer not null default 1,
  status            text not null default 'new',         -- 'new','in_progress','done','cancelled',...
  notes             text,                                -- per-item notes (“extra hot”, etc.)
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

alter table public.order_items add constraint order_items_status_check
  check (status in ('new', 'in_progress', 'done', 'cancelled'));

create index order_items_order_id_idx on public.order_items (order_id);
create index order_items_item_id_idx on public.order_items (item_id);
create index order_items_status_idx on public.order_items (status);

-- 8. Order_Item_Modifiers: applied modifiers per order item.
-- This supports many modifiers per item, and also ad-hoc ones.
create table public.order_item_modifiers (
  id                bigint generated by default as identity primary key,
  order_item_id     bigint not null references public.order_items(id) on delete cascade,
  modifier_id       bigint references public.modifiers(id) on delete set null,
  label             text not null,              -- e.g., 'Extra Shot', 'No Cheese'
  price_delta       numeric(10,2) not null default 0.00,
  created_at        timestamptz not null default now()
);

create index order_item_modifiers_order_item_id_idx
  on public.order_item_modifiers (order_item_id);

-- 9. Order_Item_Status_Events: history of status transitions.
-- This is what you’ll use to see how long each item took to prepare.
create table public.order_item_status_events (
  id                bigint generated by default as identity primary key,
  order_item_id     bigint not null references public.order_items(id) on delete cascade,
  old_status        text,                      -- can be null for the first event (from null -> 'new')
  new_status        text not null,
  created_at        timestamptz not null default now()
);

create index order_item_status_events_item_id_idx
  on public.order_item_status_events (order_item_id);
create index order_item_status_events_created_at_idx
  on public.order_item_status_events (created_at);
