-- Queue table for Cup Label print jobs. One row per OrderItem transition to
-- in_progress where the item's Category requires a label. The app only ever
-- inserts (never updates); the Print Agent (running on the venue LAN, using
-- a service-role key that bypasses RLS) updates status to 'handed_off' once
-- it has sent the label to the printer. No printer ack in v1 - 'handed_off'
-- means sent to the printer, not confirmed printed.
-- 'cancelled' is set by the Print Agent itself, at startup, if whoever is
-- running it chooses to discard a pending backlog rather than work through
-- it - never set automatically. See print-agent/agent.py.
create table public.print_jobs (
  id                bigint generated by default as identity primary key,
  order_item_id     bigint not null references public.order_items(id) on delete cascade,
  status            text not null default 'pending',
  created_at        timestamptz not null default now(),
  handed_off_at     timestamptz
);

alter table public.print_jobs add constraint print_jobs_status_check
  check (status in ('pending', 'handed_off', 'cancelled'));

create index print_jobs_status_idx on public.print_jobs (status);
create index print_jobs_order_item_id_idx on public.print_jobs (order_item_id);

-- Enable RLS
alter table public.print_jobs enable row level security;

-- Authenticated (browser) users can read and insert; only the Print Agent's
-- service-role key updates status, bypassing RLS entirely.
create policy "Authenticated users can read print_jobs"
  on public.print_jobs for select
  to authenticated
  using (true);

create policy "Authenticated users can insert print_jobs"
  on public.print_jobs for insert
  to authenticated
  with check (true);

-- Enable realtime so the Print Agent can subscribe to new jobs
alter publication supabase_realtime add table public.print_jobs;
